### ISSUE TITLE
【优化】滑动应该允许选择常用定位的元素与整个页面的滑动

### ISSUE THREAD

**Issue by LiuJingtest** [SonicCloudOrg/sonic-client-web#105]
坐标的获取
1. 元素可以获取到 size 和 location，通过两者可以计算出中心坐标
2. 整个页面，可以通过 app 的尺寸来进行获取计算中心坐标

坐标获取后，再计算出一些滑动的起止点。两个参数：划分比例（不填给个默认值），滑动方向。
比如说按比例为 percent，中心坐标为 x，y，尺寸：width，height

上滑：
        starty = y + height * (percent - 1) / percent
        endy = y + height / percent
        startx = endx = x + width * 1 / 2
下滑：
        starty = y + height * 1 / percent
        endy = y + height * (percent - 1) / percent
        startx = endx = x + width * 1 / 2
左滑：
        startx = x + width * (percent - 1) / percent
        endx = x + width / percent
        starty = endy = y + height * 1 / 2
右滑：
        startx = x + width / percent
        endx = x + width * (percent - 1) / percent
        starty = endy = y + height * 1 / 2

**Comment by ZhouYixun** [comment]
根据控件滑动，已经有了，你研究下。
页面滑动不准的，没有坐标来的准，后面会加入相对坐标的
