### ISSUE TITLE
feat：增加套件参数

### ISSUE THREAD

**Issue by GFB214** [SonicCloudOrg/sonic-client-web#233]
在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：

-  [x] 标题为fix、feat或doc开头
 - [x] 我已检查没有与此请求重复的拉取请求。
 - [x] 我已经考虑过，并确认这份呈件对其他人很有价值。
 - [x] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
 
填写PR内容：增加套件参数

**Comment by ZhouYixun** [comment]
link https://github.com/SonicCloudOrg/sonic-server/issues/302
