### ISSUE TITLE
[Q] 进入手机操作页面后如何不自动初始化 UIAutomator2 Server，有开关吗

### ISSUE THREAD

**Issue by freedomdym** [SonicCloudOrg/sonic-client-web#247]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.0.5版本

### Deploy platform

docker

### Minimal reproduce step

进入页面后会自动初始化UIAutomator2 Server，有开关可以自定义不自动初始化吗
![image](https://github.com/SonicCloudOrg/sonic-client-web/assets/25544893/5b897941-c21f-49e3-9ed2-be51f0d4e9f5)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
目前没有，以后或许会补上

**Comment by freedomdym** [comment]
了解了，感谢回复
