### ISSUE TITLE
[Bug] Android devices screen black

### ISSUE THREAD

**Issue by sam80180** [SonicCloudOrg/sonic-client-web#267]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.4.2

### Deploy platform

Linux

### Minimal reproduce step

When open 2 or more Android devices at the same time, sometimes devices' screens failed to load (incorrect size, all black, and no responses). The screen websocket is still receiving binary data when I interact with the device, e.g. click the "locate device" button.

I'm not sure this is related to jmuxer or sonic-agent's scrcpy jar.

Help needed.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
You need to wait for the image to load before switching to another page
