### ISSUE TITLE
[Bug] iOS17手机，web client报错wda初始化失败，无法打开wda

### ISSUE THREAD

**Issue by iOrangeTea** [SonicCloudOrg/sonic-client-web#268]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.2

### Deploy platform

Macosx

### Minimal reproduce step

选中连接设备，无法投屏

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
所有类似的工具目前都不支持ios17，请耐心等待，感谢

**Comment by jeniva** [comment]
IOS17现在支持了吗，我看perfdog好像可以了
