### ISSUE TITLE
【需求】想做一个前端界面右上角存在问题反馈（用户操作过程遇到的问题记录）及公告（版本更新）的能力，想问下内部是否已经有在做及规划？

### ISSUE THREAD

**Issue by lixf6** [SonicCloudOrg/sonic-client-web#271]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

略

### Deploy platform

略

### Minimal reproduce step

参考：
![image](https://github.com/SonicCloudOrg/sonic-client-web/assets/63722217/0e9fcbc4-8637-495c-b248-fc6d6f1f27a0)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
反馈给谁？公告源在哪里发布？

**Comment by lixf6** [comment]
反馈用户及目的：所有前端登陆client的用户，用以告知版本发布的变动点、操作手册等、节假日可能的断电维护等（这批用户基本都是内网用户，懵懂小白较多，希望能登陆后直接告知）；
公告源：应该会在后端设计一个类似于apphub一样的收集需求表及发布公共的表，然后起一个界面列表维护（含需求列表、公告列表、需求模板等）

**Comment by ZhouYixun** [comment]
感觉是平台外的东西，应该不考虑做。你个人有需要可以内部二开
