### ISSUE TITLE
[Bug] 获取应用列表概率性失败

### ISSUE THREAD

**Issue by jeniva** [SonicCloudOrg/sonic-client-web#273]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.3

### Deploy platform

agent window10
server web都是Linux上docker一键部署

### Minimal reproduce step

点击使用手机->点击性能监测-->获取App列表，提示加载还是获取不到
![image](https://github.com/SonicCloudOrg/sonic-client-web/assets/8514029/5a2352d2-a9d5-451b-9dc0-e2594858cfd9)
我看日志是socket断开连接
![image](https://github.com/SonicCloudOrg/sonic-client-web/assets/8514029/5bb0af5a-cc53-4aff-bdc1-c34efffa6ff4)
之前还出现过一次获取不全，然后现在是手机root的都直接获取不到了

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
什么手机？而且root过的手机不在我们的范围内，，
