### ISSUE TITLE
[Bug] iOS横屏获取控件元素坐标不对

### ISSUE THREAD

**Issue by huililuoyu** [SonicCloudOrg/sonic-client-web#276]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

Sonic 版本:2.6.4

### Deploy platform

Linux

### Minimal reproduce step

iOS进入横屏应用、点击获取控件元素、获取的坐标与实际位置错乱。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
我这边复现不了，你是进入页面后竖屏再横屏的吗？如果不对，也可以点右侧校准坐标来修复
