### ISSUE TITLE
[Bug] 安卓微信小程序webview调试，复制控件定位无效

### ISSUE THREAD

**Issue by YeungHoiChiu** [SonicCloudOrg/sonic-client-web#281]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

Linux, docker

### Minimal reproduce step

1. 获取到webview调试
2. 右键标签复制selector、xpath……
3. 没有复制成功～
![image](https://github.com/SonicCloudOrg/sonic-client-web/assets/44832826/4cf38924-4773-475e-966f-9500dc33adfb)
![image](https://github.com/SonicCloudOrg/sonic-client-web/assets/44832826/b5046ffb-e49c-4502-a9ba-d7285a1db697)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by YeungHoiChiu** [comment]
本地启动agent+我本机chrome devtools，发现可以复制，也许是目前web基础镜像中的chrome浏览器版本太低了

**Comment by YeungHoiChiu** [comment]
查了一些资料，应该是因为http（除了localhost、127.0.0.1这些）时不允许使用navigate.clipboard相关方法

**Comment by ZhouYixun** [comment]
> 查了一些资料，应该是因为http（除了localhost、127.0.0.1这些）时不允许使用navigate.clipboard相关方法

是因为iframe的权限问题，这个目前无解

**Comment by ZhouYixun** [comment]
有人提过将devtools内置进去web里面 https://discord.com/channels/1182530185749344307/1182530720544079974/1220205357113016360 但是最近暂时没去看

**Comment by YeungHoiChiu** [comment]
> 有人提过将devtools内置进去web里面 https://discord.com/channels/1182530185749344307/1182530720544079974/1220205357113016360 但是最近暂时没去看

@ZhouYixun 看到一个定期自动打包的仓库 https://github.com/iam-medvedev/chrome-devtools?tab=readme-ov-file

**Comment by ZhouYixun** [comment]
> > 有人提过将devtools内置进去web里面 https://discord.com/channels/1182530185749344307/1182530720544079974/1220205357113016360 但是最近暂时没去看
> 
> @ZhouYixun 看到一个定期自动打包的仓库 https://github.com/iam-medvedev/chrome-devtools?tab=readme-ov-file

打包不是问题，workflow可以解决，只是我暂时没时间去整这个

**Comment by YeungHoiChiu** [comment]
> > > 有人提过将devtools内置进去web里面 https://discord.com/channels/1182530185749344307/1182530720544079974/1220205357113016360 但是最近暂时没去看
> > 
> > 
> > @ZhouYixun 看到一个定期自动打包的仓库 https://github.com/iam-medvedev/chrome-devtools?tab=readme-ov-file
> 
> 打包不是问题，workflow可以解决，只是我暂时没时间去整这个

好的，我目前在尝试，已经用workflow打包chrome最新的devtools frontend了，但是新版本的文件夹放到项目public里npm run dev会报错，试了一些官方npm里一些较新的版本都是这样，只有discord那个朋友分享的那个版本试了可以，你有什么建议吗
```
> public/chrome_devtools/front_end/third_party/puppeteer/package/lib/esm/puppeteer/api/JSHandle.js:119:15: error: Class static blocks are not supported yet
    119 │         static {
        ╵                ^


error when starting dev server:
Error: Build failed with 9 errors:
public/chrome_devtools/front_end/third_party/puppeteer/package/lib/esm/puppeteer/api/ElementHandle.js:167:15: error: Class static blocks are not supported yet
public/chrome_devtools/front_end/third_party/puppeteer/package/lib/esm/puppeteer/api/Frame.js:191:15: error: Class static blocks are not supported yet
public/chrome_devtools/front_end/third_party/puppeteer/package/lib/esm/puppeteer/api/JSHandle.js:118:15: error: Class static blocks are not supported yet
public/chrome_devtools/front_end/third_party/puppeteer/package/lib/esm/puppeteer/api/JSHandle.js:119:15: error: Class static blocks are not supported yet
public/chrome_devtools/front_end/third_party/puppeteer/package/lib/esm/puppeteer/api/Page.js:159:15: error: Class static blocks are not supported yet

```

**Comment by YeungHoiChiu** [comment]
很费解，npm install之后再把front_end放进来，有时候是可以运行，先放front_end进来再npm install，vite启动就报错。。。
