### ISSUE TITLE
[feat] 自动化测试步骤支持步骤在if-else模块内(外)自由拖动更改位置

### ISSUE THREAD

**Issue by YeungHoiChiu** [SonicCloudOrg/sonic-client-web#287]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

All

### Minimal reproduce step

<img width="1012" alt="image" src="https://github.com/SonicCloudOrg/sonic-client-web/assets/44832826/3dba7ad5-e520-4ff0-bebc-f8b4bceed902">

- 如果实现起来不难，我应该会自己提pr

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
done, thanks!
