### ISSUE TITLE
[Q]运行python脚本后，后续步骤无法继续进行，python脚本包含初始化driver

### ISSUE THREAD

**Issue by U-uU** [SonicCloudOrg/sonic-client-web#299]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.0.7

### Deploy platform

Linux

### Minimal reproduce step

1、在ui自动化里添加一些步骤，
2、添加一个python脚本，脚本中初始化AndroidDriver，使用的库为：[sonic-uiautomator2-python-client](https://github.com/SonicCloudOrg/sonic-uiautomator2-python-client)，
3、在脚本步骤后，添加其他步骤，后续步骤无法正常运行

是不是因为初始化driver对象占用了sessionid呢？

![image](https://github.com/user-attachments/assets/1779103b-aa95-4f75-8872-215b5a712f33)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你是根据官方文档的做法，先关闭了sonic的driver是吗？

**Comment by U-uU** [comment]
> 你是根据官方文档的做法，先关闭了sonic的driver是吗？

你好，感谢回复！
我没有先关闭sonic的driver，我是根据这个文档最后的test_demo来编写的脚本，“直接用Sonic已启动的appium-uiautomator2-server测试的示例脚本”，而在脚本步骤后面的其他步骤就会失败，（以及获取控件元素的功能也会失败
https://soniccloudorg.github.io/doc/doc-script.html#%E4%BA%8C%E3%80%81python%E8%84%9A%E6%9C%AC

报错：
![image](https://github.com/user-attachments/assets/1141f6c4-908d-4259-9ab5-02c4315afce1)

**Comment by ZhouYixun** [comment]
> > 你是根据官方文档的做法，先关闭了sonic的driver是吗？
> 
> 你好，感谢回复！ 我没有先关闭sonic的driver，我是根据这个文档最后的test_demo来编写的脚本，“直接用Sonic已启动的appium-uiautomator2-server测试的示例脚本”，而在脚本步骤后面的其他步骤就会失败，（以及获取控件元素的功能也会失败 https://soniccloudorg.github.io/doc/doc-script.html#%E4%BA%8C%E3%80%81python%E8%84%9A%E6%9C%AC
> 
> 报错： ![image](https://private-user-images.githubusercontent.com/52627320/383033330-1141f6c4-908d-4259-9ab5-02c4315afce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTA3NjUsIm5iZiI6MTczMDc5MDQ2NSwicGF0aCI6Ii81MjYyNzMyMC8zODMwMzMzMzAtMTE0MWY2YzQtOTA4ZC00MjU5LTlhYjUtMDJjNDMxNWFmY2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA3MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NmY4YmJjOWNkMjVjMjY5ODNhNDE4N2M2ZjllMmE0YTgyMDYyZjdlNmExYjllZTEyNjAzOTIyYmM0MzI4MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iIvDJcZewAlmCVb9_Ar4rFs7HrUawdf2UYsbe3OUFRk)

方便看一下脚本吗

**Comment by U-uU** [comment]
> > > 你是根据官方文档的做法，先关闭了sonic的driver是吗？
> > 
> > 
> > 你好，感谢回复！ 我没有先关闭sonic的driver，我是根据这个文档最后的test_demo来编写的脚本，“直接用Sonic已启动的appium-uiautomator2-server测试的示例脚本”，而在脚本步骤后面的其他步骤就会失败，（以及获取控件元素的功能也会失败 https://soniccloudorg.github.io/doc/doc-script.html#%E4%BA%8C%E3%80%81python%E8%84%9A%E6%9C%AC
> > 报错： ![image](https://private-user-images.githubusercontent.com/52627320/383033330-1141f6c4-908d-4259-9ab5-02c4315afce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTA3NjUsIm5iZiI6MTczMDc5MDQ2NSwicGF0aCI6Ii81MjYyNzMyMC8zODMwMzMzMzAtMTE0MWY2YzQtOTA4ZC00MjU5LTlhYjUtMDJjNDMxNWFmY2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA3MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NmY4YmJjOWNkMjVjMjY5ODNhNDE4N2M2ZjllMmE0YTgyMDYyZjdlNmExYjllZTEyNjAzOTIyYmM0MzI4MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iIvDJcZewAlmCVb9_Ar4rFs7HrUawdf2UYsbe3OUFRk)
> 
> 方便看一下脚本吗

import os
import sys
import json
import time, datetime
session_id, adb_serial_num, global_pramas, uia_url = sys.argv[1:]
from common.models import AndroidSelector
from uia2.driver import AndroidDriver
driver = AndroidDriver(uia_url)
# 找到所有进入教室按钮
enter_classroom_buttons = []
enter_classroom_buttons = driver.find_element_list(AndroidSelector.XPATH, "//android.widget.TextView[@text='进入教室']")
#print(f"共有{len(enter_classroom_buttons)}个进入教室按钮")
#print([(e.get_rect().x + e.get_rect().y) >> 1 for e in enter_classroom_buttons])

# 点击第一个进入教室按钮-进入直播间
enter_classroom_buttons[0].click()

**Comment by ZhouYixun** [comment]
![image](https://github.com/user-attachments/assets/6a496949-3579-4755-b482-35ed094f784c)

**Comment by ZhouYixun** [comment]
你sonic版本太旧了

**Comment by U-uU** [comment]
> 你sonic版本太旧了

不好意思，我之前搞错了，我的版本应该是2.6.0，我的脚本是可以成功运行的，只是它后面的会失败“the session is not known”

**Comment by ZhouYixun** [comment]
> > 你sonic版本太旧了
> 
> 不好意思，我之前搞错了，我的版本应该是2.6.0，我的脚本是可以成功运行的，只是它后面的会失败“the session is not known”

```
if __name__ == '__main__':
    # uia_url 在 v2.5.3 更新后才有
    session_id, adb_serial_num, global_pramas, uia_url = sys.argv[1:]
    print(session_id, adb_serial_num, global_pramas, uia_url)
```

这里有sessionid打印吗

**Comment by ZhouYixun** [comment]
uia_url和session_id确认下有没有

**Comment by ZhouYixun** [comment]
或者你直接复制官网demo，跑完看看后面的步骤动不动

**Comment by U-uU** [comment]
> 或者你直接复制官网demo，跑完看看后面的步骤动不动

我复制了官网demo运行，打印了uia_url和session_id，但是后续的步骤还是一样失败，报错是一样的

![image](https://github.com/user-attachments/assets/9a7f81d4-9284-477b-aac8-bb363e589b81)

**Comment by ZhouYixun** [comment]
> > 或者你直接复制官网demo，跑完看看后面的步骤动不动
> 
> 我复制了官网demo运行，打印了uia_url和session_id，但是后续的步骤还是一样失败，报错是一样的
> 
> ![image](https://private-user-images.githubusercontent.com/52627320/383070546-9a7f81d4-9284-477b-aac8-bb363e589b81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTczODQsIm5iZiI6MTczMDc5NzA4NCwicGF0aCI6Ii81MjYyNzMyMC8zODMwNzA1NDYtOWE3ZjgxZDQtOTI4NC00NzdiLWFhYzgtYmIzNjNlNTg5YjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA4NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMzUyMzhkNTM4ZDdhOGNmNGJhZmNhZWU2NDA4ZjcyZDVlODFmYzhkYWYxODEzNGY3OWUzMWY0NTM3M2FmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YVCx1rqsFKOyEquabX895S0oLdxEAgPW1P3j3KeH-iM)

emmm，那我要抽时间看看，感谢反馈

**Comment by ZhouYixun** [comment]
应该这样是可以的，你再试试看？

**Comment by U-uU** [comment]
> , session_id=session_id

真的可以了！原来如此，十分感谢！

还想问一下，请问多窗口模式下的控件元素可以获取到吗，我好像没看到有相关的方法

**Comment by ZhouYixun** [comment]
我明天看看

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-agent/blob/main/src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java#L166

几种模式，其实是对uia2发送setting，再获取控件

对应方法是这个

https://github.com/SonicCloudOrg/sonic-uiautomator2-python-client/blob/main/uia2/driver.py#L60

**Comment by ZhouYixun** [comment]
你也反馈了自定义文档的问题，我已经更改了driver的部分，感谢
