### ISSUE TITLE
支持小程序吗

### ISSUE THREAD

**Issue by dongann** [SonicCloudOrg/sonic-client-web#300]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

支持小程序吗

### Deploy platform

支持小程序吗

### Minimal reproduce step

支持小程序吗

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
可以试一下哦
