### ISSUE TITLE
【Bug】关联项目BUG

### ISSUE THREAD

**Issue by cooler1779** [SonicCloudOrg/sonic-client-web#45]
多开项目时 关联项目id 切换项目id时 用例id不会跟着切

https://user-images.githubusercontent.com/41600632/140896584-b108399a-dc44-4c37-9342-3e3d50bcb8fe.mp4

**Comment by JayWenStar** [comment]
看不到视频。。这个是不是前端问题

**Comment by ZhouYixun** [comment]
> 看不到视频。。这个是不是前端问题

是前端问题
