### ISSUE TITLE
【feat】前端页面建议需要添加搜索，优化的地方

### ISSUE THREAD

**Issue by upengfei** [SonicCloudOrg/sonic-client-web#58]
1、希望可以在测试用例的“模块名称”、“版本名称”、“设计人”处添加筛选功能
2、希望在添加控件元素这里添加搜索功能，原因是添加的控件元素到一定数目之后，逐页翻很难找到想要的控件。
3、希望在控件元素这里添加和用例一样的分模块功能，便于查看和分类
4、公共步骤添加搜索功能
5、公共步骤选择时需要增加搜索功能
6、APP页面元素操作后有打开时间，加的强制等待无法保证下一个操作的元素一定出现
建议：增加智能等待

**Comment by dongyi0412** [comment]
您好，我有在公共步骤增加步骤那里，增加筛选功能。希望可以通过pr（作为一个初学者，第一次尝试贡献）
