### ISSUE TITLE
【建议】用例执行时增加手动停止功能

### ISSUE THREAD

**Issue by xuhanjian** [SonicCloudOrg/sonic-client-web#76]
手动中断用例执行进程
![image](https://user-images.githubusercontent.com/31010682/148176210-d7e21b9f-f33e-475c-b558-9d7169246d7d.png)

**Comment by xuhanjian** [comment]
这个功能1.3.0没上嘛 @ZhouYixun

**Comment by ZhouYixun** [comment]
> 这个功能1.3.0没上嘛 @ZhouYixun

没有，你可以关注官网和社区的更新进度
