### ISSUE TITLE
【BUG】远控界面选择关联项目无法切换显示对应项目内容

### ISSUE THREAD

**Issue by xuhanjian** [SonicCloudOrg/sonic-client-web#77]
![image](https://user-images.githubusercontent.com/31010682/148189466-67a21624-4c0a-44d9-93fd-02f1fe6df36b.png)

**Comment by ZhouYixun** [comment]
已知bug，还没修复 。详见https://github.com/SonicCloudOrg/sonic-client-web/issues/45。修复进度看那边，这个重复issue我先关闭了哦~
