### ISSUE TITLE
【建议】iOS控件元素定位增加一个常用集合定位findElements(by);

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#78]
iOS常见列表页面，同页面每个控件都是这样（如图），能通过XCUIElementTypeImage集合定位相对稳定且准确定位
![image](https://user-images.githubusercontent.com/28779574/148478803-775cea0c-a733-4a93-a3a7-bfff152a20ea.png)

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-client-web/issues/74 目前已经有计划了，你看看这个做出来效果如何
