### ISSUE TITLE
【优化】脚本运行快，手机画面还没反应完成，导致自动化脚本失败

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#79]
自动化常遇到的问题，例子：自动化脚本有3个操作步骤，实际运行时，脚本运行很快，手机还在第一步画面，脚本已经在运行第二步找控件。这样就导致第二步脚本运行失败：控件找不到，
优化：每个步骤做延迟等待1-2秒，或者每个步骤控件做时间轮询：5秒内控件找不到就失败。5内找到控件就继续往下走
目的：增加脚本稳定性，现在同个脚本，运行5次，有2次是失败的，随着步骤越来越多，这个问题越明显，iOS和安卓都考虑下。

**Comment by ZhouYixun** [comment]
目前是需要人为增加一点强制等待，在【增加步骤】->【特殊步骤】->【强制等待】里面加。
后面应该会做成用户自定义每个步骤间隔时间吧，但是目前这样会ios问题多一点，因为ios控件能找到，但是界面还没渲染的情况很多，属于ios特性，所以人为加能避归。
我暂时issue关一下，我后面找个版本加一下步骤间隔吧，感谢关注~
