### ISSUE TITLE
【invalid】控件元素无法删除

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#81]
![image](https://user-images.githubusercontent.com/28779574/148483741-41af085b-9592-4891-b816-1c561a2dbc23.png)
去控件元素里删除，提示：删除失败！控件元素已存在于步骤id：11中！  实际，测试用例里步骤ID11我已经删除了。iOS自动化测试

**Comment by ZhouYixun** [comment]
这个需要在【新增公共步骤】->【步骤列表】里面删除，这个逻辑有点奇怪，下版本会改掉
