### ISSUE TITLE
【优化】记录：手机图片已配置好，升级版本后，变成默认图片？（数据库图片字段有之前配置好的图片链接）

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#82]
记录：手机图片已配置好，升级版本后，变成默认图片？（数据库图片字段有之前配置好的图片链接）

**Comment by ZhouYixun** [comment]
这个跟你操作有关系。
如果是集群版，你可能删除了keepfiles文件夹内容
如果是simple，你可能动了docker默认挂载目录的东西
这一块在优化，感谢关注
