### ISSUE TITLE
【建议】已编辑好的测试用例和元素控件，各自能有复制功能，提高编写效率

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#84]
![image](https://user-images.githubusercontent.com/28779574/148508143-26a58c64-55b3-4381-a175-a1a4026cb999.png)
![image](https://user-images.githubusercontent.com/28779574/148508251-dc12dd42-1d7b-44eb-b671-d9d82ff5930f.png)

**Comment by ZhouYixun** [comment]
不错的想法！可以

**Comment by aovenus** [comment]
今天深度使用后，也发现需要这个。

**Comment by ZhouYixun** [comment]
> 今天深度使用后，也发现需要这个。

好的

**Comment by dongyi0412** [comment]
不知道你是否有时间处理，我可以尝试写这个接口和前端。

**Comment by ZhouYixun** [comment]
> 不知道你是否有时间处理，我可以尝试写这个接口和前端。

你微信联系我一下？

**Comment by dongyi0412** [comment]
那最好不过，你的微信是多少我加一下你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-client-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-client-web] 【建议】已编辑好的测试用例和元素控件，各自能有复制功能，提高编写效率 (Issue #84)





  
不知道你是否有时间处理，我可以尝试写这个接口和前端。
  
你微信联系我一下？

**Comment by ZhouYixun** [comment]
> 那最好不过，你的微信是多少我加一下你。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SonicCloudOrg/sonic-client-web" ***@***.***&gt;; 发送时间:&nbsp;2022年5月21日(星期六) 晚上9:59 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SonicCloudOrg/sonic-client-web] 【建议】已编辑好的测试用例和元素控件，各自能有复制功能，提高编写效率 (Issue #84) 不知道你是否有时间处理，我可以尝试写这个接口和前端。 你微信联系我一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

那你是怎么得知这个平台的？有点好奇，联系方式的话可以去官网右上角的【联系我们】找到
