### ISSUE TITLE
【优化】不能复制完整xpath路径，鼠标无法操作

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#86]
![image](https://user-images.githubusercontent.com/28779574/148520621-79b2b67c-1fef-4718-a4b8-a66bbbdc29c0.png)

**Comment by ZhouYixun** [comment]
故意的，不希望你们复制整段，希望能用xpath语法。
后面我搭配推荐xpath那个feat一起做了吧，我先关闭
