### ISSUE TITLE
[优化]远程控制页，切换到控制元素列表，再返回远程控制页，还要重新初始化

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#87]
远程控制页，切换到控制元素列表，再返回远程控制页，还要重新初始化
![image](https://user-images.githubusercontent.com/28779574/148521930-6cacb4dc-9898-40c7-8072-dcded39a9a63.png)

实际场景：在远程控制页，添加了控件元素，发现刚刚添加的控件元素有错误，要修改，只能去控制元素列表，修改后，返回重新选择设备，手机重新初始化等等，麻烦些。
在远程控制页，添加控件元素错误，重新加个新的就好？从长期使用考虑，会累积添加很多错误/不使用的元素控件，
建议：在远程控制页，可以再编辑已添加的控件元素。

**Comment by ZhouYixun** [comment]
可以，其实有这个需求。
