### ISSUE TITLE
[bug]运行用例顺序混乱

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#88]
![image](https://user-images.githubusercontent.com/28779574/148530320-201f2ab6-5860-4aeb-8705-4da582975280.png)
未运行前：关联的用例显示排序是，先3后5.
运行时：关联的用例显示排序是，先5后3。然后实际运行手机上面用例效果也是先5后3

**Comment by JayWenStar** [comment]
可以的话，提供下agent端的日志

**Comment by ZhouYixun** [comment]
我们迁移完orm框架之后你再看看，就是看看v1.3.0-beta2还有没有这个问题
