### ISSUE TITLE
【bug】同设备同用例多点几个运行，排队

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#89]
![image](https://user-images.githubusercontent.com/28779574/148530858-5c6ec458-9282-45af-9e10-e252ea7ab3a5.png)
iOS例子：ID:7，正在运行，ID:8，9正在等待进行。一下子点击中断7，8，9。设备还在运行脚本效果，拔掉数据线也还在运行脚本的效果。可能ios卡顿延迟问题，导致一些特殊情况下，中断命令或者其他操作异常

**Comment by JayWenStar** [comment]
虽然很想说提供日志，但IOS的udid大概率被截断了。。建议加作者微信排查下

**Comment by ZhouYixun** [comment]
需要提供日志哦
