### ISSUE TITLE
【bug】测试套件有2个用例，第一运行通过，测试结果就直接显示测试通过

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#96]
![image](https://user-images.githubusercontent.com/28779574/148714942-3da92d2d-458c-4c2f-9aff-c001abe2c194.png)
例子：这个测试套件我关联2个用例，第一个用例测试结果是通过，第二个用例还在运行中。结果这里就已经显示测试通过。

**Comment by ZhouYixun** [comment]
beta2已经改了这个了，过两天你看看
