### ISSUE TITLE
【优化】iOS点击获取控件元素到显示，部分机型花费时间过长

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#98]
版本：v1.3.0-beta2
![image](https://user-images.githubusercontent.com/28779574/148888985-f3eb6c99-db90-473c-ba2f-ff5085d41e20.png)
iOS点击获取控件元素到显示，计时花了36秒，第一次36秒，后面基本获取要29秒
设备：苹果xR  14.7.1

**Comment by ZhouYixun** [comment]
后面我换个截屏方案尝试下

**Comment by ZhouYixun** [comment]
这个受技术限制了，延期一下
