### ISSUE TITLE
【优化】测试报告详情，各个用例耗时总和还大于总耗时？

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-client-web#99]
![image](https://user-images.githubusercontent.com/28779574/148915426-85c12348-8462-4641-bce3-04945dc88d68.png)

**Comment by JayWenStar** [comment]
因为是并行的，所以用例耗时总和!=套件时间。

举个例子：
- 比如只有一台设备、一个套件、两个用例，用例A花的时间是5秒，用例B也花了5秒。
- 但是B用例等待A释放设备用了10秒。
- 那么用例的时间就是A花了5秒，B花了15秒（5+10）
- 最终B的花费时间是接近于整个套件的执行时间的，也可以看到你最后一条用例花的时间几乎等于总耗时，所以这严格来说不是BUG
